export const RMQ_PATTERNS = {
  USER_CREATED: 'user_created',
  USER_GET_PROFILE: 'USER_GET_PROFILE',
  USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
  AUTH_VALIDATE_TOKEN: 'AUTH_VALIDATE_TOKEN',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_UPDATE_PASSWORD: 'AUTH_UPDATE_PASSWORD',

  // Project Service
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE_VISIBILITY: 'PROJECT_UPDATE_VISIBILITY',
  PROJECT_GET_BY_ID: 'PROJECT_GET_BY_ID',

  // Hackathon Service
  HACKATHON_CREATE: 'HACKATHON_CREATE',
  HACKATHON_GET_ALL: 'HACKATHON_GET_ALL',
  HACKATHON_GET_BY_ID: 'HACKATHON_GET_BY_ID',
  HACKATHON_REGISTER: 'HACKATHON_REGISTER',
  HACKATHON_CREATE_TEAM: 'HACKATHON_CREATE_TEAM',
  HACKATHON_GET_TEAM: 'HACKATHON_GET_TEAM',
  HACKATHON_SUBMIT_PROJECT: 'HACKATHON_SUBMIT_PROJECT',
};