export const RMQ_PATTERNS = {
  USER_CREATED: 'user_created',
  USER_GET_PROFILE: 'USER_GET_PROFILE',
  USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
  AUTH_VALIDATE_TOKEN: 'AUTH_VALIDATE_TOKEN',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_UPDATE_PASSWORD: 'AUTH_UPDATE_PASSWORD',
};